name: Build Flutter Windows App

on:
  push:
    branches: [ master ]

env:
  MONGODB_URL: mongodb://192.168.1.88:27017/proclinic
  APP_ENV: production
  SOCKET_SERVER_TYPE: local

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.7' # or stable

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Cache Pub
        uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\AppData\Local\Pub\Cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
      
      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: C:\hostedtoolcache\windows\flutter
          key: ${{ runner.os }}-flutter-sdk

      - name: Install dependencies
        run: flutter pub get

      - name: Generate .env file
        run: |
          echo "MONGODB_URL=mongodb://192.168.1.88:27017/proclinic" >> .env
          echo "SOCKET_SERVER_TYPE=local" >> .env

      - name: Build Windows app
        run: flutter build windows --release --dart-define-from-file=.env

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/x64/runner/Release/